[workspace]
name = "imbalanced-learn"
channels = ["https://prefix.dev/conda-forge"]
platforms = ["osx-arm64"]
preview = ["pixi-build"]

[package]
name = { workspace = true }
authors = ["imbalanced-learn developers"]
description = "Toolbox for imbalanced dataset in machine learning"
version = "0.14.0.dev0"

[package.build.backend]
channels = [
  "https://prefix.dev/conda-forge",
]
name = "pixi-build-python"
version = "*"

[package.build.config]
noarch = true

[package.build.source]
path = "imbalanced-learn"

[package.build-dependencies]
python = "~=3.13.0"

[package.host-dependencies]
uv = "*"
python = "~=3.13.0"
setuptools = "*"

[package.run-dependencies]
python = "~=3.13.0"
numpy = ">=1.25.2,<3"
scipy = ">=1.11.4,<2"
joblib = ">=1.2.0,<2"
threadpoolctl = ">=3.1.0,<4"
scikit-learn = { path = "../scikit-learn" }

[feature.source.dependencies]
ninja = "*"
scikit-learn = { path = "../scikit-learn" }
imbalanced-learn = { path = "." }

[feature.dev.dependencies]
ipykernel = "*"
ipython = "*"
jupyterlab = "*"
twine = "*"

[feature.docs.dependencies]
matplotlib = ">=3.7.3,<4"
seaborn = ">=0.12.2,<1"
memory_profiler = ">=0.61.0,<1"
numpydoc = ">=1.5.0,<2"
sphinx = ">=8.0.2,<9"
sphinx-gallery = ">=0.13.0,<1"
sphinxcontrib-bibtex = ">=2.4.1,<3"
sphinx-copybutton = ">=0.5.2,<1"
pydata-sphinx-theme = ">=0.15.4,<1"
sphinx-design = ">=0.6.1,<1"

[feature.optional.dependencies]
pandas = ">=2.0.3,<3"

[feature.keras.dependencies]
keras = ">=3.3.3,<4"

[feature.tests.dependencies]
packaging = ">=23.2,<25"
pytest = ">=7.2.2,<9"
pytest-cov = ">=4.1.0,<6"
pytest-xdist = ">=3.5.0,<4"

[feature.docs.tasks]
build-docs = { cmd = "make html", cwd = "imbalanced-learn/doc" }
clean-docs = { cmd = "rm -rf _build/ && rm -rf auto_examples/ && rm -rf reference/generated/", cwd = "imbalanced-learn/doc" }

[feature.lint.tasks]
lint = { cmd = "pre-commit install && pre-commit run -v --all-files --show-diff-on-failure", cwd = "imbalanced-learn" }

[feature.tests.tasks]
tests = { cmd = "pytest -vsl --cov=imblearn --cov-report=xml imblearn", cwd = "imbalanced-learn" }

[environments]
dev = { features = ["source", "dev", "docs", "lint", "tests", "optional", "keras"], no-default-feature = true }
