[workspace]
name = "skops"
channels = ["https://prefix.dev/conda-forge"]
platforms = ["osx-arm64"]
preview = ["pixi-build"]

[package]
name = { workspace = true }
authors = ["skops developers"]
description = "A set of tools, related to machine learning in production"
version = "0.14.0.dev0"

[package.build.backend]
channels = [
  "https://prefix.dev/conda-forge",
]
name = "pixi-build-python"
version = "*"

[package.build.config]
noarch = true

[package.build.source]
path = "skops"

[package.build-dependencies]
python = "*"

[package.host-dependencies]
uv = "*"
python = "*"
hatchling = "*"

[package.run-dependencies]
python = "*"
numpy = ">=1.25.2,<3"
scipy = ">=1.11.4,<2"
joblib = ">=1.2.0,<2"
threadpoolctl = ">=3.1.0,<4"
scikit-learn = { path = "../scikit-learn" }
prettytable = ">=3.9.0,<4"
packaging = ">17.0"

[feature.source.dependencies]
ninja = "*"
scikit-learn = { path = "../scikit-learn" }
skops = { path = "." }

[feature.dev.dependencies]
ipykernel = "*"
ipython = "*"
jupyterlab = "*"
twine = "*"

[feature.docs.dependencies]
fairlearn = ">=0.7.0"
matplotlib = ">=3.3"
pandas = ">=1"
sphinx = ">=3.2.0"
sphinx-gallery = ">=0.7.0"
sphinx-rtd-theme = ">=1"
numpydoc = ">=1.0.0"
sphinx-prompt = ">=1.3.0"
sphinx-issues = ">=1.2.0"

[feature.optional.dependencies]
rich = ">=12"

[feature.tests.dependencies]
pytest = ">=7"
pytest-cov = ">=2.9.0"
flake8 = ">=3.8.2"
types-requests = ">=2.28.5"
flaky = ">=3.7.0"
rich = ">=12"
matplotlib = ">=3.3"
pandas = ">=1"
lightgbm = ">=3"
xgboost = ">=1.6"

[feature.lint.tasks]
lint = { cmd = "pre-commit install && pre-commit run -v --all-files --show-diff-on-failure", cwd = "skops" }

[feature.tests.tasks]
tests = { cmd = "pytest -vsl --cov=skops --cov-report=xml --cov-report=term-missing -m \"not inference\" skops" }

[environments]
dev = { features = ["source", "dev", "docs", "lint", "tests", "optional"], no-default-feature = true }
