[workspace]
name = "skore-local-project"
channels = ["https://prefix.dev/conda-forge"]
platforms = ["osx-arm64"]
preview = ["pixi-build"]

[package]
name = { workspace = true }
authors = ["skore developers"]
description = "Own your data science"
version = "0.11.0.dev0"

[package.build.backend]
channels = [
  "https://prefix.dev/conda-forge",
]
name = "pixi-build-python"
version = "*"

[package.build.config]
noarch = true

[package.build.source]
path = "skore-local-project/skore-local-project"

[package.build-dependencies]
python = "*"

[package.host-dependencies]
uv = "*"
python = "*"
hatchling = "*"

[package.run-dependencies]
python = "*"
diskcache = "*"
joblib = "*"
platformdirs = "*"
rich = "*"

[feature.source.dependencies]
skore-local-project = { path = "." }

[feature.dev.dependencies]
ipykernel = "*"
ipython = "*"
jupyterlab = "*"

[environments]
dev = { features = ["source", "dev"], no-default-feature = true }